### ISSUE TITLE
ReadPSD Node: Auto-Add Shuffle nodes for file layers

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#167] opened 2015-08-19 04:30 UTC
Hello Olear,

Can you implement a special feature button to the ReadPSD node to auto add shuffle nodes for every layer in the loaded file? For example, If PSD or XCF files has two or more layers, we can click on a button to automatically generate Shuffle nodes assigned to each layer to extract and merge.

When working with tons of layers in either format, having to create a shuffle node for each layer is an time consuming process and non efficient workflow.

Thanks

**Comment by devernay** [comment] 2015-08-19 10:39
This would have to be a pyplug or python code, which instanciates the readpsd, and then generates either the shuffle or the merge nodes. I think Nuke has such a thing for PSD.

**Comment by olear** [comment] 2015-08-19 10:48
Duplicate of #127 

Progress has stalled due my my limited Python skills ;)

**Closed by olear** 2015-08-19 10:48 UTC
